from setuptools import setup, find_packages

setup(
    name='reddit-reposter',
    version='2.2.5',
    url='https://github.com/avg333/reddit-reposter',
    author='Adrian Villar Gesto',
    author_email='adrian.villar.gesto@gmail.com',
    description='Upload to the Twitter platform a post of the chosen subreddit',
    packages=find_packages(),
    install_requires=[
        'certifi==2025.7.14',
        'charset-normalizer==3.4.2',
        'dnspython==2.7.0',
        'idna==3.10',
        'oauthlib==3.3.1',
        'pillow==11.3.0',
        'praw==7.8.1',
        'prawcore==2.4.0',
        'pymongo==4.13.2',
        'requests==2.32.4',
        'requests-oauthlib==2.0.0',
        'setuptools==80.9.0',
        'tweepy==4.16.0',
        'update-checker==0.18.0',
        'urllib3==2.5.0',
        'websocket-client==1.8.0',
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.12',
    ],
)
