name: Reddit Repost Bot

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  repost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Python Environment
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12
          architecture: x64

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Execute Repost Bot
        env:
          DB_URL: ${{ secrets.DB_URL }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          SUBREDDIT: ${{ secrets.SUBREDDIT }}
        run: python main.py --subreddit $SUBREDDIT